### ISSUE TITLE
Generated config file does not properly include ""

### ISSUE THREAD

**Issue by abebehailu** [crs4/flatehr#46]
FlatEHR Version: 1.1.0

Running the following command  `flatehr generate skeleton web_template.json` on your [test json](https://github.com/crs4/flatehr/blob/develop/tests/resources/web_template.json) generates a config file which does not properly set "" around suffix keys. 

Result: 

```yaml
...
  ctx/category: #  required
    maps_to: []
    suffixes:
      |code:
...
```

Expected:

```yaml
...
  ctx/category: #  required
    maps_to: []
    suffixes:
      "|code":
...
```
